---
url: "http://petstore.swagger.io/v2/swagger.json"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"
envs:
  dev:
    project-one: "http://petstore.swagger.io/v2/dev/project-one.json"
    project-two: "http://petstore.swagger.io/v2/dev/project-two.json"
  test:
    project-one: "http://petstore.swagger.io/v2/test/project-one.json"
    project-two: "http://petstore.swagger.io/v2/test/project-two.json"
  uat:
    project-one: "http://petstore.swagger.io/v2/uat/project-one.json"
