---
url: "http://petstore.swagger.io/v2/swagger.json"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"
envs:
  dev:
    sync: "http://petstore.swagger.io/v2/dev/sync.json"
    gateway: "http://petstore.swagger.io/v2/dev/gateway.json"
  test:
    sync: "http://petstore.swagger.io/v2/test/sync.json"
    gateway: "http://petstore.swagger.io/v2/test/gateway.json"
